// Theme token keys for palette and theme definitions

export type ThemeTokenKey =
  | 'primaryBackground'
  | 'foregroundBackground'
  | 'primaryText'
  | 'secondaryText'
  | 'tertiaryText'
  | 'accent'
  | 'border'
  | 'borderSubtle'
  | 'errorAccent'
  | 'errorBackground'
  | 'errorText'
  | 'successAccent'
  | 'successBackground'
  | 'successText'
  | 'warningAccent'
  | 'warningBackground'
  | 'warningText'
  | 'textOnBackground'
  | 'textOnPrimary'
  | 'textOnAccent'
  | 'textDisabled'
  | 'hoverBackground'
  | 'hoverPrimary'
  | 'hoverAccent'
  | 'disabledBackground'
  | 'disabledPrimary'
  | 'disabledAccent'
  | 'white'
  | 'black'